name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Hello Test
      id: hello-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Hello Test
        setup-command: ''
        command: python3 hello.py
        input: ''
        expected-output: Hello, Python World!
        comparison-method: exact
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        HELLO-TEST_RESULTS: "${{steps.hello-test.outputs.result}}"
      with:
        runners: hello-test
